### ISSUE TITLE
Highlighting does not report success or failure of the operation

### ISSUE THREAD

**Issue by profsmucker** [MahsaSeifikar/judgo#13]
When I go to highlight a region of the text to mark what is relevant, the text highlights as yellow as part of the select, but unless I click elsewhere on the document, I cannot know if the highlighting really worked or not.  I am having to learn to highlight and then click elsewhere to make sure the highlight was "accepted" by the system.  When I click to check, I discover that is is actually very hard to highlight the relevant section.  Many times the highlighting does not stick.

Either the highlighting needs to always work, or it needs to give some feedback about success or failure of the operation, i.e. was a selection actually accepted and recorded in the database?

For health misinfo, I wonder if it might simply be easier to implement something that selects whole lines rather than from character to character?

**Comment by profsmucker** [comment]
More details: The issue is that the blue selection highlight does not deactivate on failure to reveal a failure.  On success, it does change to yellow.  

This issue may not be as serious as I thought if we can teach assessors what to expect.

The issue does remain that assessors can waste lots of time trying to highlight when the highlighting refuses to work, and we should understand what this problem is.

**Comment by profsmucker** [comment]
Actually, the selection is not always blue.  In the left doc panel, the selection is yellow!  In the right it is blue.  Strange.  Is the CSS different for the right and left panels?

**Comment by MahsaSeifikar** [comment]
There is a bug related to words or phrases which are highlighted both by tags and by users. I've created a branch to solve the issue.
