### ISSUE TITLE
I cannot include Charlie or other students in issues

### ISSUE THREAD

**Issue by profsmucker** [MahsaSeifikar/judgo#14]
I can only seem to see Mahsa, Linh Nhi, and myself when I work with issues.

Is Charlie not a collaborator on this repo?  Amir and Dake should also be.

**Comment by MahsaSeifikar** [comment]
I added all of them, but they haven't accepted my request yet.

**Comment by profsmucker** [comment]
Waiting on Dake before closing issue.

**Comment by profsmucker** [comment]
All fixed.  Thanks.
