### ISSUE TITLE
Should we say what the correct answer is?

### ISSUE THREAD

**Issue by profsmucker** [MahsaSeifikar/judgo#15]
When judging docs, we can end up with incorrect docs in the correct pile by NIST assessor error, plus the "unclear" docs are sometimes, in my opinion, quite clearly wrong when we know the correct answer. 

The point being: I am almost always wanting to prefer a correct answer over anything else.  

This is really something for discussion.

**Comment by profsmucker** [comment]
I am thinking we should tell the assessor: (Assume the answer is "yes".) or (Assume the answer is "no".)

The issue then becomes what about "unclear" documents?  I am afraid of the cases where the document says "it depends" and the document is really high quality and explains the ins and outs of treatment choices.  This might be a really important document to surface and bring to the top.  

How do we induce proper preference judging behavior for these topics with multiple answers?  What is proper preference judging behavior for these search tasks?

**Comment by profsmucker** [comment]
By the way, if we don't separate the two classes of answers, then we need a complete preference ordering from one answer to the other.  

Alternatively, we would put all docs together and then instruct assessor to only be doing preference judging based on credibility of the answer (how authoritative is the source, etc.)  But here as well, I would think we'd want the preferences to go pretty deep to be sure not to give credit to runs with incorrect answers.

**Comment by profsmucker** [comment]
@claclark What are you thoughts?

**Comment by claclark** [comment]
We probably want to do both if we are computing help vs. harm. The relevant but unclear documents should go in both pools or neither pool, I suppose.

I wish we could get some statistics on stage one and two before we build the preference pools.

**Comment by profsmucker** [comment]
Closing this issue as issue #19 has decided the answer is "yes, we'll tell them the answer".
