### ISSUE TITLE
some of the tag highlighting colors are too dark and thus lack contrast with black font

### ISSUE THREAD

**Issue by profsmucker** [MahsaSeifikar/judgo#17]
All tag highlight colors should be such that they produce good contract with the black font to all use to still read the text.  Example of issue where I cannot easily read what is in blue/purple:

![image](https://user-images.githubusercontent.com/14891741/182885130-bc4c60e8-1842-4442-a90d-77b13205ca83.png)

**Comment by MahsaSeifikar** [comment]
I changed them in the latest pr.
